FROM node:22

WORKDIR /app

# Copy package.json and lock file
COPY package*.json ./

# Install dependencies
RUN npm install --legacy-peer-deps

# Copy the rest of the frontend code
COPY . .

# Rebuild rollup to fix optional dependency bug
RUN rm -rf node_modules/.cache && npm rebuild rollup

# Build the app
RUN npm run build

# Preview server
CMD ["npm", "run", "preview"]
